language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: c9cG7TrHdlZUf1RNum55MHHQBOvLrMSvBE7fA/RrC/JnLIMUkrtT8D2ZEVar/3DY5Iok+l/G4S2x6wjcoEcKJIYPFtAbdx04x1wmAa6geJRwEafHQYSSrxA1JtHUSMfu99SFWzLDpPlnwRzywfQO15TZ/GywtIHEZyEKGxMcmIGd/uHiZS/b1R3ucDucZtgxyViOiTZhulpUMdnXbzExOE2DyR2W8fw39D45plzq9YpvU6Vzrhqa+08xCvy6r/MDlr8DrjKFEJqapNjbXZRy63sVpp0nqwZsk4P5Nu7V1sjncx2NwwZoBxQvTMosCJNg6bTW1lV2mCTAeSbOCRgrZrS9DFOTxWnRZI2EaypBBq8wpwOjdXEuUFQWnqT+DbgUiOPo/5rmg0rI8dl7or1VWfCoKOa7qW0k1+y5G0zFi0xBbMnuLPYmcrFo8VQaBgVjripGsxiQ0tX+9n69ICnP3Fl7nnIEDostPmgdxpLWtbtiVI5oJf78qTfUiQ0YuM43xn53FuD/MMJwX8Hu74pxOI7HsVTGtnhgW0qE005Tj/OPR7RGyyillqbObPa0FRMQERzJ+TBcnAk4tTHlug5HCau3TWmn5YSWkyWiA05Ub8rZz0LGcWCmo0jrjQV6XQ0osazADifpSnUgRYisi5ZCn6vG33buVEvtr3Ztv98PyZ4=
  app: obscure-mesa-31828
  on:
    repo: mee213/node-shopping-list-integration-tests
